---
- name: "Install web server packages"
  apt:
    name: "{{ webdev_packages }}"
    state: present

- name: "Start nginx service"
  service:
    name: "{{ webdev_service_name }}"
    state: "{{ webdev_service_state }}"
    enabled: "{{ webdev_service_enabled }}"

- name: "Create simple test page"
  copy:
    content: |
      <html>
      <head><title>Test Server - {{ inventory_hostname }}</title></head>
      <body>
      <h1>Hello from {{ inventory_hostname }}!</h1>
      <p>Web server is working!</p>
      <p>Server IP: {{ ansible_host }}</p>
      <p>OS: {{ ansible_distribution }} {{ ansible_distribution_version }}</p>
      </body>
      </html>
    dest: "{{ webdev_document_root }}/{{ webdev_index_file }}"

- name: "Web setup complete"
  debug:
    msg: "Web server ready at http://{{ ansible_host }} (accessible via http://localhost:{{ ansible_port | default(webdev_default_port) }})"