---
- name: "Install web server packages"
  apt:
    name: "{{ webdev_packages }}"
    state: present

- name: "Start nginx service"
  service:
    name: "{{ webdev_service_name }}"
    state: "{{ webdev_service_state }}"
    enabled: "{{ webdev_service_enabled }}"

- name: "Deploy custom index page from template"
  template:
    src: index.html.j2
    dest: "{{ webdev_document_root }}/{{ webdev_index_file }}"
    owner: root
    group: root
    mode: '0644'
  notify: restart nginx

- name: "Web setup complete"
  debug:
    msg: "Web server ready at http://{{ ansible_host }} (accessible via http://localhost:{{ ansible_port | default(webdev_default_port) }})"