---
- name: "Update package cache"
  apt:
    update_cache: true
  when: ansible_os_family == "Debian"

- name: "Install basic packages"
  package:
    name:
      - curl
      - wget
      - git
      - htop
    state: present

- name: "Ensure SSH is running"
  service:
    name: ssh
    state: started
    enabled: true