---
- name: "Test connectivity"
  ping:
  register: ping_result
  failed_when: false
  tags:
    - connectivity
    - health-check
    - never  # Only runs when explicitly called
  
- name: "Verify connectivity successful"
  fail:
    msg: "Unable to connect to {{ inventory_hostname }}. Please check SSH connectivity."
  when: ping_result.ping is not defined
  tags:
    - connectivity
    - health-check

- name: "Update package cache (Debian/Ubuntu)"
  apt:
    update_cache: true
  when: ansible_distribution in ["Ubuntu", "Debian"]
  register: apt_update_result
  retries: 3
  delay: 10
  until: apt_update_result is succeeded
  ignore_errors: true
  tags:
    - packages
    - package-cache
    - setup

- name: "Install basic packages (Debian/Ubuntu)"
  apt:
    name:
      - curl
      - wget
      - git
      - htop
    state: present
  when: ansible_distribution in ["Ubuntu", "Debian"]
  register: package_install_result
  retries: 2
  delay: 5
  until: package_install_result is succeeded
  tags:
    - packages
    - basic-tools
    - setup

- name: "Ensure SSH service exists"
  stat:
    path: /lib/systemd/system/ssh.service
  register: ssh_service_file
  tags:
    - ssh
    - security
    - services
  
- name: "Ensure SSH is running"
  service:
    name: ssh
    state: started
    enabled: true
  register: ssh_service_result
  when: ssh_service_file.stat.exists
  tags:
    - ssh
    - security
    - services
    - dangerous  # Could disrupt connection

- name: "Show completion message"
  debug:
    msg: "Basic setup completed successfully on {{ inventory_hostname }} ({{ ansible_distribution }})"
  tags:
    - setup
    - reporting