---
- name: "Install Python development packages"
  apt:
    name:
      - python3-pip
      - python3-dev
      - python3-full
      - python3-venv
      - build-essential
    state: present

- name: "Create analytics virtual environment"
  command: python3 -m venv /opt/analytics-env
  args:
    creates: /opt/analytics-env

- name: "Install basic Python data science packages in virtual environment"
  pip:
    name:
      - jupyter
      - pandas
      - numpy
      - matplotlib
      - jupyterlab
    virtualenv: /opt/analytics-env

- name: "Create jupyter config directory"
  file:
    path: /root/.jupyter
    state: directory
    mode: '0755'

- name: "Create simple jupyter config"
  copy:
    content: |
      c.ServerApp.ip = '0.0.0.0'
      c.ServerApp.port = 8888
      c.ServerApp.open_browser = False
      c.ServerApp.token = ''
      c.ServerApp.password = ''
      c.ServerApp.allow_root = True
    dest: /root/.jupyter/jupyter_lab_config.py

- name: "Create startup script for Jupyter"
  copy:
    content: |
      #!/bin/bash
      cd /root
      source /opt/analytics-env/bin/activate
      jupyter lab --config=/root/.jupyter/jupyter_lab_config.py
    dest: /usr/local/bin/start-jupyter
    mode: '0755'

- name: "Create analytics environment activation script"
  copy:
    content: |
      #!/bin/bash
      source /opt/analytics-env/bin/activate
      echo "Analytics environment activated!"
      echo "To start Jupyter Lab: /usr/local/bin/start-jupyter"
      echo "Or run: jupyter lab --config=/root/.jupyter/jupyter_lab_config.py"
      echo "Python packages available: jupyter, pandas, numpy, matplotlib"
    dest: /usr/local/bin/activate-analytics
    mode: '0755'

- name: "Analytics setup complete"
  debug:
    msg: "Analytics server ready on {{ inventory_hostname }} - Run '/usr/local/bin/start-jupyter' to start Jupyter Lab on port 8888"