---
all:
  children:
    webdev:
      hosts:
        webdev-01:
          ansible_host: 172.20.0.11
          ansible_port: 22
          ansible_user: root
          ansible_password: ansible123 #not suitable for prod
          server_role: web
          environment: development
      vars:
        ansible_python_interpreter: /usr/bin/python3
        stack_type: lamp
        
    analytics:
      hosts:
        # Placeholder for future CentOS analytics servers
        # analytics-01:
        #   ansible_host: 172.20.0.21
        #   ansible_port: 22
        #   ansible_user: root
        #   server_role: analytics
        #   environment: development
      vars:
        ansible_python_interpreter: /usr/bin/python3
        stack_type: data_science
        
    # OS-based groups for cross-platform management
    ubuntu:
      children:
        webdev:
      vars:
        ansible_distribution: Ubuntu
        package_manager: apt
        
    centos:
      children:
        analytics:
      vars:
        ansible_distribution: CentOS
        package_manager: yum