---
all:
  children:
    webdev:
      hosts:
        webdev-01:
          ansible_host: 172.20.0.11
          ansible_port: 22
          ansible_user: root
          ansible_password: "{{ vault_ansible_password }}"
          server_role: web
          env: development
        webdev-02:
          ansible_host: 172.20.0.12
          ansible_port: 22
          ansible_user: root
          ansible_password: "{{ vault_ansible_password }}"
          server_role: web
          env: development
      vars:
        ansible_python_interpreter: /usr/bin/python3
        stack_type: lamp
        
    analytics:
      hosts:
        analytics-01:
          ansible_host: 172.20.0.21
          ansible_port: 22
          ansible_user: root
          ansible_password: "{{ vault_ansible_password }}"
          server_role: analytics
          env: development
          jupyter_port: 8888
          spark_ui_port: 4040
        analytics-02:
          ansible_host: 172.20.0.22
          ansible_port: 22
          ansible_user: root
          ansible_password: "{{ vault_ansible_password }}"
          server_role: analytics
          env: development
          jupyter_port: 8888
          spark_ui_port: 4040
      vars:
        ansible_python_interpreter: /usr/bin/python3
        stack_type: data_science
        
    # OS-based groups for cross-platform management
    ubuntu:
      children:
        webdev:
      vars:
        ansible_distribution: Ubuntu
        package_manager: apt
        
    debian:
      children:
        analytics:
      vars:
        ansible_distribution: Debian
        package_manager: apt