---
- name: "Deploy Common Configuration"
  hosts: all
  become: true
  roles:
    - common

- name: "Deploy Web Development Environment"
  hosts: webdev
  become: true
  roles:
    - webdev

- name: "Deploy Analytics Environment"
  hosts: analytics
  become: true
  roles:
    - analytics