---
- name: "Install UFW firewall"
  package:
    name: ufw
    state: present

- name: "Allow SSH through firewall"
  ufw:
    rule: allow
    port: "22"
    proto: tcp

- name: "Enable UFW"
  ufw:
    state: enabled
    policy: deny